web:
  build: .
  command: 'bash -c ''npm install; npm test'''
  working_dir: /app/user
  volumes:
   - ./:/app/user/
   - /app/user/node_modules
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
