version: 2.1

executors:
  nodejs:
    machine: true
    working_directory: ~/app
    environment:
      NODE_ENV: ci

aliases:
  - &filter_only_master
    branches:
      only: master

  - &filter_only_develop
    branches:
      only: develop

  - &filter_wip_branch
    branches:
      ignore:
        - master
        - develop

  - &compile_docker_env
    run:
      name: Init environment variables for Docker
      command: |
        touch ~/app/.env
        source ~/app/.env
        echo "DOCKER_TAG='0.0.${CIRCLE_BUILD_NUM:-0}_${CIRCLE_BRANCH}'" >> ~/app/.env
        echo "DOCKER_IMAGE_NAME='${DOCKER_APP_NAME}_web'" >> ~/app/.env
        echo "DOCKER_HUB_IMAGE_PATH='$DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG'" >> ~/app/.env
        echo "HEROKU_REGISTRY='registry.heroku.com'" >> ~/app/.env
        echo "HEROKU_IMAGE_PATH='$HEROKU_REGISTRY/$HEROKU_APP_NAME/web'" >> ~/app/.env

  - &log_docker_env
    run:
      name: Log Docker variables
      command: |
        echo CIRCLE_BRANCH: $CIRCLE_BRANCH
        echo DOCKER_TAG: $DOCKER_TAG
        echo DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME
        echo DOCKER_HUB_IMAGE_PATH: $DOCKER_HUB_IMAGE_PATH
        echo HEROKU_REGISTRY: $HEROKU_REGISTRY
        echo HEROKU_IMAGE_PATH: $HEROKU_IMAGE_PATH

  - &persist_docker_env
    persist_to_workspace:
      root: ~/app
      paths:
        - .env

  - &attach_docker_env
    attach_workspace:
      at: ~/app

  - &load_docker_env
    run:
      name: Load environment variables shared via .env file
      command: |
        cat ~/app/.env >> ${BASH_ENV:-.env.ci}
        source ~/app/.env

  - &docker_hub_login
    run:
      name: Login to Docker Hub
      command: echo $DOCKER_HUB_PASSWORD | docker login --username=$DOCKER_HUB_USERNAME --password-stdin

  - &docker_hub_pull
    run:
      name: Pull Docker image from Docker Hub
      command: |
        docker pull $DOCKER_HUB_IMAGE_PATH

  - &docker_heroku_login
    run:
      name: Login to Docker Registry on Heroku
      command: echo $HEROKU_API_KEY | docker login --username=$HEROKU_USERNAME --password-stdin $HEROKU_REGISTRY

params:
  - &env
    description: 'Angular Environment name (environment.<env>.ts)'
    default: dev
    type: string

  - &herokuapp
    description: 'Heroku application name set up for deployment'
    type: string
    default: ''

jobs:
  build:
    executor: nodejs
    parameters:
      env: *env
    steps:
      - checkout
      - *compile_docker_env
      - *load_docker_env
      - *log_docker_env
      - *persist_docker_env
      - run: docker info
      - run:
          name: Build Docker image
          command: |
            export ENV=<<parameters.env>>
            docker-compose -p $DOCKER_APP_NAME build web
            docker tag $DOCKER_IMAGE_NAME $DOCKER_HUB_IMAGE_PATH
      - *docker_hub_login
      - run:
          name: Deploy image to Docker Hub
          command: |
            docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME

  test:
    executor: nodejs
    steps:
      - *attach_docker_env
      - *load_docker_env
      - *log_docker_env
      - *docker_hub_login
      - *docker_hub_pull
      - run:
          name: Test
          command: |
            docker run --rm $DOCKER_HUB_IMAGE_PATH npm test

  deploy:
    executor: nodejs
    parameters:
      herokuapp: *herokuapp
    steps:
      - *attach_docker_env
      - *load_docker_env
      - *log_docker_env
      - *docker_hub_login
      - *docker_hub_pull
      - *docker_heroku_login
      - run:
          name: Deploy image to Heroku (Registry)
          command: |
            export HEROKU_APP_NAME=<<parameters.herokuapp>>
            docker tag $DOCKER_HUB_IMAGE_PATH $HEROKU_IMAGE_PATH
            docker push $HEROKU_IMAGE_PATH
      - run:
          name: Release app on Heroku
          command: |
            export HEROKU_APP_NAME=<<parameters.herokuapp>>
            docker inspect $HEROKU_IMAGE_PATH --format={{.Id}} > WEB_DOCKER_IMAGE_ID_FILE
            export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID_FILE)
            curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
              -d '{
                "updates": [ { "type": "web", "docker_image": "'"$WEB_DOCKER_IMAGE_ID"'" } ]
              }' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $HEROKU_API_KEY"

workflows:
  version: 2

  ci:
    jobs:
      - build:
          filters: *filter_wip_branch
      - test:
          requires:
            - build

  deploy_dev:
    jobs:
      - build:
          env: dev
          filters: *filter_only_develop
      - test:
          requires:
            - build
      - deploy:
          herokuapp: heroku-docker-nodejs-custom-dev
          requires:
            - test

  deploy_prod:
    jobs:
      - build:
          env: prod
          filters: *filter_only_master
      - test:
          requires:
            - build
      - deploy_hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # It only runs the "hold" job when deploy has succeeded
            - test
      - deploy:
          herokuapp: heroku-docker-nodejs-custom
          requires:
            - deploy_hold
