version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: touch .env

     - setup_remote_docker

     # test
     - run: |
         docker-compose -f docker-compose.unittests.yml run --rm unittests

     # build image
     - run: |
         docker info
         docker-compose -f docker-compose.yml -p herokudockernodejscustom build web

     # deploy image
     - run: |
         set -eu -o pipefail
         echo $HEROKU_API_KEY | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com

         TAG="0.0.${CIRCLE_BUILD_NUM}"
         docker tag herokudockernodejscustom_web registry.heroku.com/$HEROKU_APP_NAME/web:$TAG
         docker tag herokudockernodejscustom_web registry.heroku.com/$HEROKU_APP_NAME/web:latest

         docker push registry.heroku.com/$HEROKU_APP_NAME/web

         # release
         docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}} > WEB_DOCKER_IMAGE_ID_FILE
         export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID_FILE)
         curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -d '{ "updates": [ { "type": "web", "docker_image": "'"$WEB_DOCKER_IMAGE_ID"'" }]}' \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"
