version: 2.1

executors:
  nodejs:
    machine: true
    working_directory: ~/app
    # docker:
    #   - image: circleci/node:12.2.0
    environment:
      NODE_ENV: ci

aliases:
  - &filter_only_master
    branches:
      only: master

  - &filter_only_develop
    branches:
      only: develop

  - &filter_wip_branch
    branches:
      ignore:
        - master
        - develop

  - &log_branch
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}

  - &init_docker_env
    run:
      name: Init environment variables for Docker
      command: |
        export DOCKER_TAG="0.0.${CIRCLE_BUILD_NUM:-0}"
        export DOCKER_IMAGE_NAME=${DOCKER_APP_NAME}_web

  - &docker_hub_login
    run:
      name: Login to Docker Hub
      command: echo $DOCKER_HUB_PASSWORD | docker login --username=$DOCKER_HUB_USERNAME --password-stdin

params:
  - &env
    description: 'Angular Environment name (environment.<env>.ts)'
    default: dev
    type: string

  - &herokuapp
    description: 'Heroku application name set up for deployment'
    type: string
    default: ''

jobs:
  build:
    executor: nodejs
    parameters:
      env: *env
    steps:
      - *log_branch
      - checkout
      # - setup_remote_docker
      - *init_docker_env
      - run: touch .env
      - run: docker info
      - run:
          name: Build Docker image
          command: |
            # set -eu -o pipefail
            export ENV=<<parameters.env>>
            docker-compose -p $DOCKER_APP_NAME build web
            docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$DOCKER_TAG
      - *docker_hub_login
      - run:
          name: Deploy image to Docker Hub
          command: |
            # set -eu -o pipefail
            docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG
            docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME

  test:
    executor: nodejs
    steps:
      - *log_branch
      # - setup_remote_docker
      - *init_docker_env
      - *docker_hub_login
      - run:
          name: Pull Docker image under test
          command: |
            docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG
      - run:
          name: Test
          command: |
            docker run --rm $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_TAG npm test

  deploy:
    executor: nodejs
    parameters:
      herokuapp: *herokuapp
    steps:
      - *log_branch
      # - setup_remote_docker
      - *init_docker_env
      - *docker_hub_login
      - run:
          name: Deploy image to Heroku (Registry)
          command: |
            # set -eu -o pipefail
            docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG registry.heroku.com/<<parameters.herokuapp>>/web
            docker push registry.heroku.com/<<parameters.herokuapp>>/web

  release:
    executor: nodejs
    parameters:
      herokuapp: *herokuapp
    steps:
      - *log_branch
      # - setup_remote_docker
      - *init_docker_env
      - run:
          name: Release app on Heroku
          command: |
            docker inspect registry.heroku.com/<<parameters.herokuapp>>/web --format={{.Id}} > WEB_DOCKER_IMAGE_ID_FILE
            export WEB_DOCKER_IMAGE_ID=$(cat WEB_DOCKER_IMAGE_ID_FILE)
            curl -n -X PATCH https://api.heroku.com/apps/<<parameters.herokuapp>>/formation \
               -d '{ "updates": [ { "type": "web", "docker_image": "'"$WEB_DOCKER_IMAGE_ID"'" }]}' \
             -H "Content-Type: application/json" \
             -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
             -H "Authorization: Bearer $HEROKU_API_KEY"

workflows:
  version: 2

  build:
    jobs:
      - build:
          filters: *filter_wip_branch
      - test:
          requires:
            - build

  deploy_dev:
    jobs:
      - build:
          env: dev
          filters: *filter_only_develop
      - test:
          requires:
            - build
      - deploy:
          herokuapp: heroku-docker-nodejs-custom
          requires:
            - test

  build_prod:
    jobs:
      - build:
          filters: *filter_only_master
      - test:
          requires:
            - build
      - deploy:
          herokuapp: heroku-docker-nodejs-custom
          requires:
            - test
      - release_hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # It only runs the "hold" job when deploy has succeeded
            - deploy
      - release:
          herokuapp: heroku-docker-nodejs-custom
          requires:
            - release_hold
